'''version'''
__version__ = '0.1.0'
'''author'''
__author__ = 'Zhenchao Jin'
'''title'''
__title__ = 'CSSegmentation'
'''description'''
__description__ = 'CSSegmentation: An Open Source Continual Semantic Segmentation Toolbox Based on PyTorch'
'''url'''
__url__ = 'https://github.com/SegmentationBLWX/cssegmentation'
'''email'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'Apache License 2.0'
'''copyright'''
__copyright__ = 'Copyright 2023-2030 Zhenchao Jin'